services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-container
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: sua_senha_root_segura
      MARIADB_DATABASE: embrapac
      MARIADB_USER: agenor
      MARIADB_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - default_network
    # healthcheck:
    #   test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
    #   timeout: 20s
    #   retries: 10
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  flyway:
    image: flyway/flyway:latest
    command: migrate
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - ./migrations:/flyway/sql
    environment:
      FLYWAY_URL: jdbc:mariadb://mariadb:3306/embrapac
      FLYWAY_USER: agenor
      FLYWAY_PASSWORD: admin123
    networks:
      - default_network

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto-mqtt
    restart: unless-stopped
    ports:
      - "18833:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - default_network

volumes:
  mariadb_data:
    driver: local

networks:
  default_network:
    driver: bridge
